# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'pull_request'
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    - name: 'Populate auth file with SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.SFDX_URL}} > SFDX_QA'
      
    - name: 'Authenticate to Production Org'
      run: sfdx auth:sfdxurl:store -f SFDX_QA -s -a production
      
    - name: 'Run deploy'
      run: sfdx force:source:deploy -x manifest/package.xml --testlevel RunLocalTests --json
